### ISSUE TITLE
wrong bearing coordinates for arrow/corridors with direction west

### ISSUE THREAD

**Issue by aaknai** [spatialillusions/nvg#10]
When I tried to use your library in some cases I got wrong coordinates for arrow.
After a bit of frustration I got that it's depends of the coordinates order.
If I give coordinates that goes from left to right I had no issues.
by the other hand if I want some arrow that goes from rith to left I get the 2 bearing points around the middle vertices switched each other.
In the attached zip file you can find an nvg/xml file with two parallel arrows but different directions(order of points)

to repair the arrows I have changed line  357
`feature.geometry.coordinates.push(distBearing(item.points[j], direction2 < 180 ? (item.width/2)*factor : -(item.width/2)*factor, 180+((direction1+direction2)/2)));`

and line 373

`feature.geometry.coordinates.push(distBearing(item.points[j], direction2 < 180 ? -(item.width/2)*factor : (item.width/2)*factor,  180+((direction1+direction2)/2)));`

![got](https://cloud.githubusercontent.com/assets/6787216/21360169/175bf946-c6df-11e6-8ccc-e05c7a63f5b4.PNG)

`<?xml version="1.0" encoding="UTF-8"?>
<nvg:nvg  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:nvg='https://tide.act.nato.int/schemas/2012/10/nvg'
   xsi:schemaLocation='https://tide.act.nato.int/schemas/2012/10/nvg ../../Schemas/nvg.2.0.xsd'
   version="2.0.0">
    <nvg:arrow
            label="Styled Arrow"
            uri="urn:md5:a87851c9d37e678829e1150717b5cf86"
            points="16.8,60 16.4,60 15.8,60.1"
            width="5000"
            style="stroke-width:5;fill:none;stroke-opacity:0.5;">
        <nvg:textInfo>Example arrow for documentation</nvg:textInfo>
    </nvg:arrow>
    <nvg:arrow
            label="Styled Arrow 2"
            uri="urn:md5:a87851c9d37e678829e1150717b5cf82"
            points="15.8,61.1 16.4,61 16.8,61"
            width="5000"
            style="stroke-width:5;fill:none;stroke-opacity:0.5;">
        <nvg:textInfo>Example arrow for documentation</nvg:textInfo>
    </nvg:arrow>
</nvg:nvg>`

**Comment by spatialillusions** [comment]
Thank you very much for your input, I have implemented your suggested changes and hopefully everything will be working now. Let me know if you find anything else, I have had a limited set of sample data so it might be other things that I have missed.

**Comment by aaknai** [comment]
You are welcome.
despite some issues that cam be found I really appreciate your work on this library as well as the one regarding Military Simbology for units.

Corridors have the same issue of arrows:
![got](https://cloud.githubusercontent.com/assets/6787216/21382774/b7ed2096-c762-11e6-9baa-f9b18d83f0c2.PNG)

After changing line 405:

```javascript
feature.geometry.coordinates[0].push(distBearing(item.points[j], direction2 < 180 ? (item.width/2)*factor : -(item.width/2)*factor, 180+((direction1+direction2)/2)));
```

and line 416:
```javascript
feature.geometry.coordinates[0].push(distBearing(item.points[j],direction2 < 180 ? -(item.width/2)*factor : (item.width/2)*factor, 180 + ((direction1+direction2)/2)));
```

![expected](https://cloud.githubusercontent.com/assets/6787216/21382784/c2b24326-c762-11e6-9f5b-925bfd9bb423.PNG)

following the xml used:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<nvg:nvg  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:nvg='https://tide.act.nato.int/schemas/2012/10/nvg'
   xsi:schemaLocation='https://tide.act.nato.int/schemas/2012/10/nvg ../../Schemas/nvg.2.0.xsd'
   version="2.0.0">
    <nvg:corridor
            uri="urn:md5:a87851c9d37e678829e1150717b5cf86"
            points="16.8,60 16.4,60 15.8,60.1"
            width="5000"
            style="stroke-width:5;fill:none;stroke-opacity:0.5;">
    </nvg:corridor>
    <nvg:corridor
            uri="urn:md5:a87851c9d37e678829e1150717b5cf82"
            points="15.8,61.1 16.4,61 16.8,61"
            width="5000"
            style="stroke-width:5;fill:none;stroke-opacity:0.5;">
    </nvg:corridor>
</nvg:nvg>
```

**Comment by spatialillusions** [comment]
I'll fix that later today, thank you again for your input. If you find anything else please let me know.

**Comment by aaknai** [comment]
Sorry for bothering you.
After using a bit more the last commited version of nvg I realised that my
solution works for that specific cases I found but is not resolving the
problem at root.

I will analize the problem and I will come back with a real solution to the
problem

2016-12-21 10:25 GMT+01:00 Måns Beckman <notifications@github.com>:

**Comment by aaknai** [comment]
Ok got it!  I tried to use github desktop to clone your repository and then
create a new branch "arrows-and-corridors" in wich I commited the bugfix
but I'm not allowed to synch it to your repository in order to make an
official pull request.

maybe I'm doing something wrong...

2016-12-21 12:08 GMT+01:00 Attila Andrei Aknai <aa.aknai@gmail.com>:

**Comment by spatialillusions** [comment]
First make a fork to your account, then make changes and then create a pull, that should work. Or attach the updated file here and I will merge it with the existing code manually.
